export const DOMAIN_ERROR_CODES = {
	RESTAURANT_NOT_FOUND: "RESTAURANT_NOT_FOUND",
	ADDON_NOT_FOUND: "ADDON_NOT_FOUND",
	INVALID_ADDON_DATA: "INVALID_ADDON_DATA",
	CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
	CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
	INVALID_CATEGORY_DATA: "INVALID_CATEGORY_DATA",
	MENU_ITEM_ALREADY_EXISTS: "MENU_ITEM_ALREADY_EXISTS",
	INVALID_MENU_ITEM_DATA: "INVALID_MENU_ITEM_DATA",
	MENU_ITEM_NOT_FOUND: "MENU_ITEM_NOT_FOUND",
} as const;

export type DomainErrorCode =
	(typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];
