export const ONBOARDING_NEXT_STEPS = {
	ONBOARDING: "ONBOARDING",
	VERIFICATION_STATUS: "VERIFICATION_STATUS",
	SUBSCRIPTION: "SUBSCRIPTION",
	DASHBOARD: "DASHBOARD",
} as const;

export type OnboardingNextStep =
	(typeof ONBOARDING_NEXT_STEPS)[keyof typeof ONBOARDING_NEXT_STEPS];
