import { HTTP_STATUS, type HttpStatusCode } from "./http.constants.ts";

export const DOMAIN_ERROR_STATUS_MAP: Record<string, HttpStatusCode> = {
	// 404 Not Found
	USER_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
	STAFF_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
	RESOURCE_NOT_FOUND: HTTP_STATUS.NOT_FOUND,

	// 409 Conflict
	EMAIL_ALREADY_EXISTS: HTTP_STATUS.CONFLICT,
	STAFF_ALREADY_EXISTS: HTTP_STATUS.CONFLICT,
	CONFLICT: HTTP_STATUS.CONFLICT,

	// 401 Unauthorized
	INVALID_CREDENTIALS: HTTP_STATUS.UNAUTHORIZED,
	INVALID_REFRESH_TOKEN: HTTP_STATUS.UNAUTHORIZED,
	INVALID_TEMP_TOKEN: HTTP_STATUS.UNAUTHORIZED,
	REVOKED_TOKEN: HTTP_STATUS.UNAUTHORIZED,
	UNAUTHORIZED: HTTP_STATUS.UNAUTHORIZED,

	// 403 Forbidden
	STAFF_INACTIVE: HTTP_STATUS.FORBIDDEN,
	STAFF_SUSPENDED: HTTP_STATUS.FORBIDDEN,
	FORBIDDEN: HTTP_STATUS.FORBIDDEN,

	// 429 Too Many Requests
	RATE_LIMIT_EXCEEDED: HTTP_STATUS.TOO_MANY_REQUESTS,

	// 400 / 422 Bad Request / Unprocessable Entity
	INVALID_OTP: HTTP_STATUS.BAD_REQUEST,
	OTP_EXPIRED: HTTP_STATUS.BAD_REQUEST,
	INVALID_STAFF_DATA: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	INVALID_EMAIL: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	INVALID_PHONE: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	INVALID_STAFF_ROLE: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	INVALID_STAFF_STATUS: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	VALIDATION_ERROR: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	RestaurantAlreadyExistsError: HTTP_STATUS.CONFLICT,
	InvalidVerificationTokenError: HTTP_STATUS.UNAUTHORIZED,
	InvalidRefreshTokenError: HTTP_STATUS.UNAUTHORIZED,
	OtpCooldownActiveError: HTTP_STATUS.TOO_MANY_REQUESTS,
	OtpVerificationAttemptsExceededError: HTTP_STATUS.TOO_MANY_REQUESTS,
	RestaurantAccountBlockedError: HTTP_STATUS.FORBIDDEN,
};

export function getStatusCodeForDomainError(
	code: string,
	fallback: HttpStatusCode = HTTP_STATUS.INTERNAL_SERVER_ERROR,
): HttpStatusCode {
	if (DOMAIN_ERROR_STATUS_MAP[code]) {
		return DOMAIN_ERROR_STATUS_MAP[code];
	}

	if (code.startsWith("INVALID_")) {
		return HTTP_STATUS.UNPROCESSABLE_ENTITY;
	}

	if (code.endsWith("_NOT_FOUND")) {
		return HTTP_STATUS.NOT_FOUND;
	}

	if (code.endsWith("_ALREADY_EXISTS")) {
		return HTTP_STATUS.CONFLICT;
	}

	return fallback;
}
