import { DOMAIN_ERROR_CODES } from "@/domain/constants/error-code.constants.ts";
import { HTTP_STATUS, type HttpStatusCode } from "./http.constants.ts";

export const DOMAIN_ERROR_STATUS_MAP: Record<string, HttpStatusCode> = {
	USER_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
	[DOMAIN_ERROR_CODES.STAFF_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
	[DOMAIN_ERROR_CODES.RESTAURANT_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
	RESOURCE_NOT_FOUND: HTTP_STATUS.NOT_FOUND,

	[DOMAIN_ERROR_CODES.EMAIL_ALREADY_EXISTS]: HTTP_STATUS.CONFLICT,
	[DOMAIN_ERROR_CODES.STAFF_ALREADY_EXISTS]: HTTP_STATUS.CONFLICT,
	[DOMAIN_ERROR_CODES.STAFF_INVITATION_ALREADY_PENDING]: HTTP_STATUS.CONFLICT,
	[DOMAIN_ERROR_CODES.RESTAURANT_ALREADY_PROCESSED]: HTTP_STATUS.CONFLICT,
	[DOMAIN_ERROR_CODES.RESTAURANT_ALREADY_BLOCKED]: HTTP_STATUS.CONFLICT,
	[DOMAIN_ERROR_CODES.RESTAURANT_NOT_BLOCKED]: HTTP_STATUS.CONFLICT,
	CONFLICT: HTTP_STATUS.CONFLICT,

	[DOMAIN_ERROR_CODES.INVALID_CREDENTIALS]: HTTP_STATUS.UNAUTHORIZED,
	[DOMAIN_ERROR_CODES.INVALID_REFRESH_TOKEN]: HTTP_STATUS.UNAUTHORIZED,
	[DOMAIN_ERROR_CODES.INVALID_TEMP_TOKEN]: HTTP_STATUS.UNAUTHORIZED,
	[DOMAIN_ERROR_CODES.REVOKED_TOKEN]: HTTP_STATUS.UNAUTHORIZED,
	UNAUTHORIZED: HTTP_STATUS.UNAUTHORIZED,

	[DOMAIN_ERROR_CODES.STAFF_INACTIVE]: HTTP_STATUS.FORBIDDEN,
	[DOMAIN_ERROR_CODES.STAFF_SUSPENDED]: HTTP_STATUS.FORBIDDEN,
	[DOMAIN_ERROR_CODES.STAFF_FORBIDDEN]: HTTP_STATUS.FORBIDDEN,
	[DOMAIN_ERROR_CODES.RESTAURANT_ACCOUNT_BLOCKED]: HTTP_STATUS.FORBIDDEN,
	[DOMAIN_ERROR_CODES.RESTAURANT_INACTIVE]: HTTP_STATUS.FORBIDDEN,
	[DOMAIN_ERROR_CODES.FORBIDDEN_RESOURCE]: HTTP_STATUS.FORBIDDEN,
	[DOMAIN_ERROR_CODES.UNAUTHORIZED_RESTAURANT_ACCESS]: HTTP_STATUS.FORBIDDEN,
	FORBIDDEN: HTTP_STATUS.FORBIDDEN,

	[DOMAIN_ERROR_CODES.RATE_LIMIT_EXCEEDED]: HTTP_STATUS.TOO_MANY_REQUESTS,

	[DOMAIN_ERROR_CODES.INVALID_OTP]: HTTP_STATUS.BAD_REQUEST,
	[DOMAIN_ERROR_CODES.OTP_EXPIRED]: HTTP_STATUS.BAD_REQUEST,
	[DOMAIN_ERROR_CODES.INVALID_INVITATION_TOKEN]: HTTP_STATUS.BAD_REQUEST,
	[DOMAIN_ERROR_CODES.INVITATION_EXPIRED]: HTTP_STATUS.BAD_REQUEST,
	[DOMAIN_ERROR_CODES.INVALID_SORT_FIELD]: HTTP_STATUS.BAD_REQUEST,
	[DOMAIN_ERROR_CODES.INVALID_SORT_ORDER]: HTTP_STATUS.BAD_REQUEST,

	[DOMAIN_ERROR_CODES.STAFF_INVITATION_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
	[DOMAIN_ERROR_CODES.INVALID_STAFF_DATA]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_EMAIL]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_PHONE]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_STAFF_ROLE]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_STAFF_STATUS]: HTTP_STATUS.BAD_REQUEST,
	[DOMAIN_ERROR_CODES.INVALID_INVITATION_STATUS]:
		HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_RESTAURANT_DATA]:
		HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_RESTAURANT_STATUS]:
		HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_ONBOARDING_STATUS]:
		HTTP_STATUS.UNPROCESSABLE_ENTITY,
	VALIDATION_ERROR: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	RestaurantAlreadyExistsError: HTTP_STATUS.CONFLICT,
	InvalidVerificationTokenError: HTTP_STATUS.UNAUTHORIZED,
	InvalidRefreshTokenError: HTTP_STATUS.UNAUTHORIZED,
	OtpCooldownActiveError: HTTP_STATUS.TOO_MANY_REQUESTS,
	OtpVerificationAttemptsExceededError: HTTP_STATUS.TOO_MANY_REQUESTS,
	RestaurantAccountBlockedError: HTTP_STATUS.FORBIDDEN,

	[DOMAIN_ERROR_CODES.INVALID_STORAGE_KEY]: HTTP_STATUS.BAD_REQUEST,
	InvalidStorageKeyError: HTTP_STATUS.BAD_REQUEST,

	UnsupportedFileCategoryError: HTTP_STATUS.BAD_REQUEST,
	UnsupportedFileTypeError: HTTP_STATUS.BAD_REQUEST,
	FileSizeExceededError: HTTP_STATUS.BAD_REQUEST,
	UnauthorizedEntityAccessError: HTTP_STATUS.FORBIDDEN,
	InvalidEntityTypeError: HTTP_STATUS.BAD_REQUEST,
	InvalidEntityIdError: HTTP_STATUS.BAD_REQUEST,
	[DOMAIN_ERROR_CODES.ADDON_ALREADY_EXISTS]: HTTP_STATUS.CONFLICT,
	[DOMAIN_ERROR_CODES.INVALID_ADDON_DATA]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.ADDON_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
	AddonAlreadyExistsError: HTTP_STATUS.CONFLICT,
	InvalidAddonDataError: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	AddonNotFoundError: HTTP_STATUS.NOT_FOUND,
	[DOMAIN_ERROR_CODES.MENU_ITEM_ALREADY_EXISTS]: HTTP_STATUS.CONFLICT,
	[DOMAIN_ERROR_CODES.MENU_ITEM_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
	[DOMAIN_ERROR_CODES.CATEGORY_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
	[DOMAIN_ERROR_CODES.ADDON_NOT_FOUND_FOR_RESTAURANT]: HTTP_STATUS.NOT_FOUND,
	[DOMAIN_ERROR_CODES.INVALID_MENU_ITEM_DATA]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[DOMAIN_ERROR_CODES.INVALID_VARIANT_DATA]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	MenuItemAlreadyExistsError: HTTP_STATUS.CONFLICT,
	MenuItemNotFoundError: HTTP_STATUS.NOT_FOUND,
	CategoryNotFoundError: HTTP_STATUS.NOT_FOUND,
	AddonNotFoundForRestaurantError: HTTP_STATUS.NOT_FOUND,
	InvalidMenuItemDataError: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	InvalidVariantDataError: HTTP_STATUS.UNPROCESSABLE_ENTITY,
};

export function getStatusCodeForDomainError(
	code: string,
	fallback: HttpStatusCode = HTTP_STATUS.INTERNAL_SERVER_ERROR,
): HttpStatusCode {
	if (DOMAIN_ERROR_STATUS_MAP[code]) {
		return DOMAIN_ERROR_STATUS_MAP[code];
	}

	if (code.startsWith("INVALID_")) {
		return HTTP_STATUS.UNPROCESSABLE_ENTITY;
	}

	if (code.endsWith("_NOT_FOUND")) {
		return HTTP_STATUS.NOT_FOUND;
	}

	if (code.endsWith("_ALREADY_EXISTS")) {
		return HTTP_STATUS.CONFLICT;
	}

	return fallback;
}
