export const OTP_CONFIG = {
	LENGTH: 6,
	EXPIRY_SECONDS: 5 * 60,
	MAX_ATTEMPTS: 5,
	SEND_OTP_REQUEST_LIMIT: 3,
	SEND_OTP_WINDOW_SECONDS: 60 * 60,
	RESEND_OTP_REQUEST_LIMIT: 5,
	RESEND_OTP_WINDOW_SECONDS: 60 * 60,
	VERIFICATION_TOKEN_EXPIRY_SECONDS: 10 * 60,
} as const;
