const MB_IN_BYTES = 1024 * 1024;

export const MAX_FILE_SIZE_BYTES = {
	DOCUMENTS: 5 * MB_IN_BYTES,
	IMAGES: 5 * MB_IN_BYTES,
	PROFILE: 2 * MB_IN_BYTES,
	RECEIPTS: 5 * MB_IN_BYTES,
	MENUS: 10 * MB_IN_BYTES,
} as const;
